# Generated by Django 4.1.7 on 2023-03-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('obtention_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=25)),
                ('mission', models.TextField()),
                ('icon_company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_realisation', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('git_link', models.CharField(max_length=200)),
                ('image_realisation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_resssource', models.CharField(max_length=20)),
                ('url_ressource', models.CharField(max_length=100)),
                ('icon_ressource', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_competence', models.CharField(max_length=50)),
                ('image_competence', models.CharField(max_length=100)),
                ('type_competence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.type_competence')),
            ],
        ),
    ]
