# Generated by Django 4.1.7 on 2023-03-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_experience_icon_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='image_realisation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='icon_ressource',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
