# Generated by Django 4.1.7 on 2023-03-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_realisation_image_realisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='image_competence',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='image_realisation',
        ),
        migrations.AddField(
            model_name='competence',
            name='icon_competence',
            field=models.ImageField(blank=True, null=True, upload_to='icon_competence'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='icon_realisation',
            field=models.ImageField(blank=True, null=True, upload_to='icon_realisation'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='icon_company',
            field=models.ImageField(blank=True, null=True, upload_to='icon_company'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='icon_ressource',
            field=models.ImageField(blank=True, null=True, upload_to='icon_ressource'),
        ),
    ]
