# Generated by Django 4.1.7 on 2023-03-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_competence_image_competence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='icon_realisation',
            field=models.ImageField(blank=True, null=True, upload_to='.icon_realisation'),
        ),
    ]
