# Generated by Django 4.1.7 on 2023-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_realisation_icon_realisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='name_resssource',
            new_name='name_ressource',
        ),
        migrations.AlterField(
            model_name='realisation',
            name='icon_realisation',
            field=models.ImageField(blank=True, null=True, upload_to='icon_realisation'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='url_ressource',
            field=models.CharField(max_length=200),
        ),
    ]
